version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: petclinic-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: petclinic
      MYSQL_USER: petclinic
      MYSQL_PASSWORD: petclinicpassword
    ports:
      - "3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    container_name: petclinic-app
    environment:
      - MYSQL_URL=jdbc:mysql://db:3306/petclinic
      - MYSQL_USER=petclinic
      - MYSQL_PASS=petclinicpassword
      - SPRING_PROFILES_ACTIVE=mysql
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  db_data:


