version: '3.8'

services:
  jenkins-agent:
    build: .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - JAVA_OPTS=-Xmx512m
    networks:
      - jenkins-network

networks:
  jenkins-network:
    driver: bridge
