apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: spring-petclinic-dev
spec:
  selector:
    app: mysql-deployment
  type: NodePort
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
    nodePort: 30700
