apiVersion: v1
kind: Service
metadata:
  name: spring-petclinic-service
  namespace: spring-petclinic-dev
spec:
  selector:
    app: spring-petclinic
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30300
