apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: spring-petclinic-dev
spec:
  capacity:
    storage: 512Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: mysql-class
  local:
    path: /home/docker/volumes/spring-mysql
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - minikube
