apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim-log-1
spec:
  selector:
    matchLabels:
      name: pv-log
  resources:
    requests:
      storage: 50Mi
  accessModes:
    - ReadWriteMany
