apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  MYSQL_DATABASE: c3FsMDE=  # sql01 base64 encoded
  MYSQL_USER: dXNlcjE=  # user1 base64 encoded
  MYSQL_PASSWORD: cGFzc3dvcmQ=  # password base64 encoded
  MYSQL_ROOT_PASSWORD: cGFzc3dvcmQxMjM=  # password123 base64 encode
