apiVersion: v1
kind: Pod
metadata:
  name: yellow
spec:
  containers:
  - name: lemon
    image: busybox
    command: ['sh', '-c', 'echo Hello from lemon && sleep 3600']
  - name: gold
    image: redis